pipx install black
pipx install cfn-lint
pipx install coiled
pipx install docutils
pipx install ec2instanceconnectcli
pipx install hardeneks
pipx install isort
pipx install kube-shell
pipx install pip-tools
pipx install voila
