# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = '$aws$kubernetes$directory$git_branch$git_commit$git_state$git_status$character'


[aws]
format = '[$symbol($profile )](172)'
symbol = '☁️  '

[character]
success_symbol = ' [»](105 bold)'
error_symbol = ' [»](105 bold)'

[directory]
format = '[$path](32)'
home_symbol = '~'
truncate_to_repo = false
truncation_length = 111111

[git_branch]
symbol = ''
format =  '[\(](68)[$symbol$branch](42)[\)](68)'
truncation_length = 100000
truncation_symbol = ''
ignore_branches = []

[git_commit]
commit_hash_length = 7
only_detached = true
tag_disabled = false
tag_symbol = ''

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[PICKING](bold red)'

[git_status]
ahead = '⇡'
behind = '⇣'
conflicted = '='
deleted = '✘'
disabled = false
diverged = '⇕'
format = '([\[$all_status$ahead_behind\]]($style))'
ignore_submodules = false
modified = '!'
renamed = '»'
staged = '+'
stashed = '\\$'
style = 'red bold'
untracked = '?'
up_to_date = ''

[golang]
disabled = true
symbol = 'go '
style = '122'

[kubernetes]
disabled = false
format = '[$symbol$context:$namespace]($style) '
style = '67'

[line_break]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true
symbol = 'py'
version_format = ' v${raw}'
style = '33 bold'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[terraform]
disabled = true
